# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfe604211e40e6799817530dbf56cc263300fa4e14a6ae776b869bfe41fb7bc068bba4c06971748320e7c4192d000d3aae76355f835df8f4134baa7ef3b542b2

test:
  secret_key_base: 8fda0fb063b9a20ea61de6e23bc94e559f8aad52ae29496a3231c35e121f89c01b88922e02f314891246a5097232aac5bfca12893b5f6cd4e80cc2cb426eedd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
